// Generated by Wrangler on Sat Sep 07 2024 19:39:51 GMT+0900 (Korean Standard Time)
// by running `wrangler types`

interface Env {
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUPABASE_ANON_KEY: string;
	AWS_ACCESS_KEY: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENAI_API_KEY: string;
}
