// Generated by Wrangler on Sun Sep 08 2024 01:42:14 GMT+0900 (Korean Standard Time)
// by running `wrangler types`

interface Env {
	COORDINATES_KV: KVNamespace;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUPABASE_ANON_KEY: string;
	AWS_ACCESS_KEY: string;
	AWS_SECRET_ACCESS_KEY: string;
	OPENAI_API_KEY: string;
}
